name = "tasks"
description = "Benchmark tasks"
version = "0.1.0-dev"

authors = ["Kay-Uwe Kirstein"]
maintainers = ["Kay-Uwe Kirstein <kay-uwe@kirsteinhome.ch>"]
maintainers-logins = ["kkirstein"]
licenses = "MIT"
website = ""
tags = ["benchmark"]

[[depends-on]]
image_io = "^20240725.0.0"
